module.exports = [{
  "question":{
    "attachment":{
      "type":"image",
      "payload":{
        "url":"http://i.imgur.com/bvgRsBv.jpg",
        "is_reusable":true
      }
    }
  }, 
  "answer":{}
},{
  "question":{
    "text":"為什麼耶穌打不到蚊子？"
  },
  "answer":{
    "attachment":{
      "type":"image",
      "payload":{
        "url":"http://i.imgur.com/WUJPehQ.jpg",
        "is_reusable":true
      }
    }
  }
},{
  "question":{
    "attachment":{
      "type":"image",
      "payload":{
        "url":"https://i.imgur.com/9jTUhts.png",
        "is_reusable":true
      }
    }
  },
  "answer":{
    "attachment":{
      "type":"image",
      "payload":{
        "url":"https://i.imgur.com/aTf3xgv.png",
        "is_reusable":true
      }
    }
  }
},{
  "question":{
    "text":"為什麼哈利波特不吃冰？"
  },
  "answer":{
    "text":"因為魔法少年賈修"
  }
},{
  "question":{
    "text":"哪個姓氏的人脾氣最差？"
  },
  "answer":{
    "text":"呂\n\n\n\n\n\n\n\n\n屢試不爽"
  }
},{
  "question":{
    "text":"為什麼獨角仙會絕種？"
  },
  "answer":{
    "text":"因為牠是甲蟲"
  }
},{
  "question":{
    "text":"哪一個相態做錯事會被原諒？"
  },
  "answer":{
    "text":"氣態，因為他不是固液的"
  }
},{
  "question":{
    "text":"害羞的嬸嬸，猜一個藝人"
  },
  "answer":{
    "text":"畢書盡"
  }
},{
  "question":{
    "text":"這台車為什麼跑這麼快？"
  },
  "answer":{
    "text":"我想其中另有引擎"
  }
},{
  "question":{
    "text":"頂新是甚麼顏色？"
  },
  "answer":{
    "text":"垃圾"
  }
},{
  "question":{
    "text":"哪個殺手只會說英文？"
  },
  "answer":{
    "text":"銀翼殺手"
  }
}];
